version: "3.9"

services:
  machine:
    image: cartesi/dapp:${DAPP_NAME:?undefined DAPP_NAME}-devel-machine
    command: xxd -c 256 -p latest/hash; sleep 3
    volumes:
      - machine:/var/opt/cartesi/machine-snapshots

  deployer:
    image: juztamau5/rollups-cli:0.9.1
    depends_on:
      machine:
        condition: service_started
    command:
      [
        "create",
        "--rpc",
        "${RPC_URL:?undefined RPC_URL}",
        "--mnemonic",
        "${MNEMONIC:?undefined MNEMONIC}",
        "--templateHashFile",
        "/var/opt/cartesi/machine-snapshots/latest/hash",
        "--outputFile",
        "/deployments/${NETWORK:?undefined NETWORK}/${DAPP_NAME:?undefined DAPP_NAME}.json",
        "--validators",
        "${VALIDATORS:?undefined VALIDATORS}",
        "--gasPrice",
        "${GAS_PRICE:?undefined GAS_PRICE}",
        "--gasLimit",
        "${GAS_LIMIT:?undefined GAS_LIMIT}",
      ]
    volumes:
      - machine:/var/opt/cartesi/machine-snapshots:ro
      - ./deployments:/deployments

volumes:
  machine: {}
