version: "3.9"

services:
  hardhat:
    image: juztamau5/rollups-hardhat:devel
    command:
      [
        "node",
        "--network",
        "hardhat",
        "--export",
        "/opt/cartesi/share/blockchain/localhost.json",
      ]
    init: true
    ports:
      - "8545:8545"
    healthcheck:
      test:
        ["CMD", "test", "-f", "/opt/cartesi/share/blockchain/localhost.json"]
      interval: 10s
      timeout: 30s
      retries: 15
    volumes:
      - ./deployments:/app/rollups/deployments
      - ./export:/opt/cartesi/share/blockchain

  server_manager:
    restart: always
    ports:
      - "5001:5001"
    healthcheck:
      test: ["CMD", "grpc-health-probe", "-addr=:5001"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - machine:/opt/cartesi/share/dapp-bin
    environment:
      - SERVER_MANAGER_LOG_LEVEL=warning
      - REMOTE_CARTESI_MACHINE_LOG_LEVEL=info

  deployer:
    image: juztamau5/rollups-cli:devel
    restart: on-failure
    depends_on:
      hardhat:
        condition: service_healthy
      server_manager:
        condition: service_healthy
    command:
      [
        "create",
        "--rpc",
        "http://hardhat:8545",
        "--deploymentFile",
        "/opt/cartesi/share/blockchain/localhost.json",
        "--mnemonic",
        "test test test test test test test test test test test junk",
        "--templateHashFile",
        "/opt/cartesi/share/dapp-bin/hash",
        "--outputFile",
        "/deployments/localhost/dapp.json",
      ]
    volumes:
      - machine:/opt/cartesi/share/dapp-bin:ro
      - ./deployments:/deployments
      - ./export:/opt/cartesi/share/blockchain

  ultrachess_deployer:
    image: juztamau5/ultrachess-deployer:1.0.0
    restart: on-failure
    depends_on:
      hardhat:
        condition: service_healthy
    command:
      [
        "deploy",
        "--network",
        "docker",
        "--export",
        "/opt/cartesi/share/blockchain/localhost-ultrachess.json",
      ]
    volumes:
      - ./deployments:/app/rollups/deployments
      - ./export:/opt/cartesi/share/blockchain

  finished:
    image: hello-world:latest # Close to scratch image
    depends_on:
        deployer:
            condition: service_completed_successfully
        ultrachess_deployer:
            condition: service_completed_successfully

volumes:
  machine: {}
