version: "3"

services:
  server_manager:
    ports:
      - "5004:5004"
    environment:
      - RUST_LOG=warn

  deployer:
    command:
      [
        "create",
        "--rpc",
        "http://hardhat:8545",
        "--deploymentFile",
        "/opt/cartesi/share/deployments/localhost.json",
        "--mnemonic",
        "test test test test test test test test test test test junk",
        # template hash is not relevant in host mode, so we can specify hash zero
        "--templateHash",
        "0x0000000000000000000000000000000000000000000000000000000000000000",
        "--outputFile",
        "/deployments/localhost/dapp.json"
      ]
